import {
  Book,
  BookOpen,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  CircleSlash,
  Clock,
  FileText,
  Laptop,
  Loader2,
  Menu,
  Moon,
  MoreVertical,
  Plus,
  Settings,
  Sun,
  Trash,
  User,
  X,
} from "lucide-react"

export const Icons = {
  logo: Book,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  user: User,
  add: Plus,
  ellipsis: MoreVertical,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  menu: Menu,
  bookOpen: BookOpen,
  fileText: FileText,
  check: CheckCircle,
  clock: Clock,
  blocked: CircleSlash,
}
